export const defaultTheme = {
  white: '#fff',
  '--color-base/white': '#ffffff',
  '--color-base/gray-6': '#f2f2f2',
  '--color-base/gray-5': '#e0e0e0',
  '--color-base/gray-4': '#bdbdbd',
  '--color-base/gray-3': '#828282',
  '--color-base/gray-2': '#4f4f4f',
  '--color-base/gray-1': '#333333',
  '--color-base/orange': '#fe8824',
  '--color-base/orange-dark': '#ff5400',
  '--color-base/orange-light': '#fff8f0',
  '--color-base/turquoise': '#00a3c4',
  '--color-base/turquoise dark-2': '#023e8a',
  '--color-base/turquoise-light': '#caf0f8',
  '--color-base/background': '#fafafa',
}
