'use client'

import { ReactNode } from 'react'

import { globalStyles } from '@/styles/global'

import { Roboto } from 'next/font/google'
const roboto = Roboto({
  weight: '400',
  style: 'normal',
  preload: false,
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

globalStyles()

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="pt-br">
      <body className={roboto.className}>{children}</body>
    </html>
  )
}
